import React, { useState, useMemo } from 'react'
import { motion } from 'framer-motion'
import {
  FileText,
  Download,
  Calendar,
  BarChart3,
  Clock,
  Target,
  Flame,
  Heart,
  Brain,
  Share2,
  Mail,
  Printer,
  CheckCircle,
  TrendingUp,
} from 'lucide-react'
import { useReducedMotion, getMotionProps } from '../hooks/useReducedMotion'

// Report types
const REPORT_TYPES = [
  {
    id: 'weekly',
    name: 'Weekly Summary',
    description: 'Tasks, focus time, and wins from the past week',
    icon: Calendar,
    color: 'blue',
  },
  {
    id: 'monthly',
    name: 'Monthly Progress',
    description: 'Detailed trends and patterns over the month',
    icon: BarChart3,
    color: 'purple',
  },
  {
    id: 'medical',
    name: 'Medical Summary',
    description: 'Formatted for sharing with healthcare providers',
    icon: Heart,
    color: 'red',
  },
  {
    id: 'coaching',
    name: 'Coaching Report',
    description: 'Detailed insights for ADHD coaches or therapists',
    icon: Brain,
    color: 'green',
  },
]

// Gather all app data
const gatherData = () => {
  const getData = (key) => {
    try {
      return JSON.parse(localStorage.getItem(key) || '[]')
    } catch {
      return []
    }
  }

  return {
    stats: getData('nero_insights_stats'),
    tasks: getData('nero_prioritized_tasks'),
    moods: getData('nero_mood_history'),
    sleep: getData('nero_sleep_history'),
    medications: getData('nero_medications'),
    reviews: getData('nero_weekly_reviews'),
    distractions: getData('nero_distraction_log'),
    timeEstimates: getData('nero_time_estimates'),
  }
}

// Calculate statistics
const calculateStats = (data, period = 7) => {
  const now = new Date()
  const startDate = new Date(now)
  startDate.setDate(startDate.getDate() - period)

  // Tasks
  const tasksCompleted = Object.values(data.stats || {})
    .reduce((sum, day) => sum + (day.tasksCompleted || 0), 0)

  // Focus sessions
  const focusSessions = Object.values(data.stats || {})
    .reduce((sum, day) => sum + (day.focusSessions || 0), 0)

  const focusMinutes = Object.values(data.stats || {})
    .reduce((sum, day) => sum + (day.focusMinutes || 0), 0)

  // Mood average
  const recentMoods = (data.moods || [])
    .filter(m => new Date(m.timestamp) >= startDate)
  const avgMood = recentMoods.length > 0
    ? (recentMoods.reduce((sum, m) => sum + m.score, 0) / recentMoods.length).toFixed(1)
    : 'N/A'

  // Sleep average
  const recentSleep = (data.sleep || [])
    .filter(s => new Date(s.date) >= startDate)
  const avgSleep = recentSleep.length > 0
    ? (recentSleep.reduce((sum, s) => sum + s.quality, 0) / recentSleep.length).toFixed(0)
    : 'N/A'

  // Medication adherence
  const medLogs = (data.medications || [])
    .filter(m => new Date(m.timestamp) >= startDate && m.taken)
  const medAdherence = medLogs.length > 0 ? 'Logged' : 'No data'

  return {
    tasksCompleted,
    focusSessions,
    focusMinutes,
    avgMood,
    avgSleep,
    medAdherence,
    daysActive: Object.keys(data.stats || {}).length,
  }
}

// Generate report content
const generateReport = (type, data, stats) => {
  const now = new Date()
  const dateStr = now.toLocaleDateString('en', { year: 'numeric', month: 'long', day: 'numeric' })

  let content = ''

  if (type === 'weekly') {
    content = `
NERO WEEKLY SUMMARY
Generated: ${dateStr}
=====================================

PRODUCTIVITY OVERVIEW
---------------------
Tasks Completed: ${stats.tasksCompleted}
Focus Sessions: ${stats.focusSessions}
Total Focus Time: ${Math.round(stats.focusMinutes / 60)} hours ${stats.focusMinutes % 60} minutes
Days Active: ${stats.daysActive}

WELLNESS INDICATORS
-------------------
Average Mood: ${stats.avgMood}/10
Average Sleep Quality: ${stats.avgSleep}%
Medication Tracking: ${stats.medAdherence}

WEEKLY WINS
-----------
${(data.reviews || []).slice(-1)[0]?.wins?.filter(w => w).join('\n- ') || 'No wins recorded this week'}

AREAS FOR FOCUS
---------------
${(data.reviews || []).slice(-1)[0]?.intentions?.filter(i => i).join('\n- ') || 'No intentions set'}

=====================================
Generated by Nero - Your ADHD Companion
    `.trim()
  }

  if (type === 'monthly') {
    content = `
NERO MONTHLY PROGRESS REPORT
Generated: ${dateStr}
=====================================

30-DAY STATISTICS
-----------------
Total Tasks Completed: ${stats.tasksCompleted}
Total Focus Sessions: ${stats.focusSessions}
Total Focus Time: ${Math.round(stats.focusMinutes / 60)} hours
Active Days: ${stats.daysActive} / 30

TRENDS
------
Average Mood Rating: ${stats.avgMood}/10
Sleep Quality Average: ${stats.avgSleep}%

TOP DISTRACTION PATTERNS
------------------------
${analyzeDistractions(data.distractions)}

TIME ESTIMATION ACCURACY
------------------------
${analyzeTimeEstimates(data.timeEstimates)}

=====================================
Generated by Nero - Your ADHD Companion
    `.trim()
  }

  if (type === 'medical') {
    content = `
ADHD MANAGEMENT SUMMARY
Patient Self-Report via Nero App
Generated: ${dateStr}
=====================================

This report is generated from self-tracking data and is intended
to supplement clinical discussion, not replace professional assessment.

MEDICATION ADHERENCE
--------------------
Tracking Status: ${stats.medAdherence}
${getMedicationSummary(data.medications)}

SLEEP PATTERNS
--------------
Average Sleep Quality: ${stats.avgSleep}%
${getSleepSummary(data.sleep)}

FUNCTIONAL OUTCOMES
-------------------
Tasks Completed (past 30 days): ${stats.tasksCompleted}
Focus Sessions Completed: ${stats.focusSessions}
Average Focus Duration: ${stats.focusSessions > 0 ? Math.round(stats.focusMinutes / stats.focusSessions) : 0} minutes

MOOD TRACKING
-------------
Average Mood Rating: ${stats.avgMood}/10
${getMoodSummary(data.moods)}

PATIENT-IDENTIFIED CHALLENGES
-----------------------------
${getChallenges(data.reviews)}

=====================================
Generated by Nero - Your ADHD Companion
For clinical use - please discuss with patient
    `.trim()
  }

  if (type === 'coaching') {
    content = `
ADHD COACHING SESSION REPORT
Generated: ${dateStr}
=====================================

CLIENT PROGRESS SUMMARY
-----------------------
Active Days: ${stats.daysActive}
Tasks Completed: ${stats.tasksCompleted}
Focus Sessions: ${stats.focusSessions}
Total Focus Time: ${Math.round(stats.focusMinutes / 60)}h ${stats.focusMinutes % 60}m

SELF-REPORTED WELLNESS
----------------------
Mood Average: ${stats.avgMood}/10
Sleep Quality: ${stats.avgSleep}%

DISTRACTION ANALYSIS
--------------------
${analyzeDistractions(data.distractions)}

TIME PERCEPTION
---------------
${analyzeTimeEstimates(data.timeEstimates)}

WEEKLY REFLECTION THEMES
------------------------
What Helped:
${getHelpedThemes(data.reviews)}

What Blocked:
${getBlockedThemes(data.reviews)}

CLIENT-SET INTENTIONS
---------------------
${getRecentIntentions(data.reviews)}

SUGGESTED DISCUSSION POINTS
---------------------------
- Review distraction patterns and coping strategies
- Discuss time estimation improvement techniques
- Celebrate wins and progress
- Adjust goals based on energy patterns

=====================================
Generated by Nero - Your ADHD Companion
    `.trim()
  }

  return content
}

// Helper functions for report generation
const analyzeDistractions = (distractions) => {
  if (!distractions || distractions.length === 0) return 'No distraction data logged'
  const typeCounts = {}
  distractions.forEach(d => {
    typeCounts[d.type] = (typeCounts[d.type] || 0) + 1
  })
  return Object.entries(typeCounts)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5)
    .map(([type, count]) => `- ${type}: ${count} occurrences`)
    .join('\n') || 'No patterns identified'
}

const analyzeTimeEstimates = (estimates) => {
  if (!estimates || estimates.length === 0) return 'No time estimation data'
  const avgAccuracy = estimates.reduce((sum, e) => sum + (e.accuracy || 100), 0) / estimates.length
  return `Average accuracy: ${Math.round(avgAccuracy)}%`
}

const getMedicationSummary = (meds) => {
  if (!meds || meds.length === 0) return 'No medication logs recorded'
  return 'See detailed medication log in app'
}

const getSleepSummary = (sleep) => {
  if (!sleep || sleep.length === 0) return 'No sleep data recorded'
  return 'Sleep patterns logged in app'
}

const getMoodSummary = (moods) => {
  if (!moods || moods.length === 0) return 'No mood data recorded'
  return 'Detailed mood tracking available in app'
}

const getChallenges = (reviews) => {
  if (!reviews || reviews.length === 0) return 'No challenges documented'
  const recent = reviews.slice(-4)
  const challenges = recent.map(r => r.blocked).filter(b => b)
  return challenges.join('\n') || 'None specified'
}

const getHelpedThemes = (reviews) => {
  if (!reviews || reviews.length === 0) return 'No data'
  const helped = reviews.slice(-4).map(r => r.helped).filter(h => h)
  return helped.join('\n') || 'None specified'
}

const getBlockedThemes = (reviews) => {
  if (!reviews || reviews.length === 0) return 'No data'
  const blocked = reviews.slice(-4).map(r => r.blocked).filter(b => b)
  return blocked.join('\n') || 'None specified'
}

const getRecentIntentions = (reviews) => {
  if (!reviews || reviews.length === 0) return 'No intentions set'
  const recent = reviews.slice(-1)[0]
  return recent?.intentions?.filter(i => i).join('\n- ') || 'None specified'
}

export default function ExportReports() {
  const prefersReducedMotion = useReducedMotion()
  const [selectedType, setSelectedType] = useState('weekly')
  const [isGenerating, setIsGenerating] = useState(false)
  const [generatedReport, setGeneratedReport] = useState(null)

  // Gather and calculate data
  const data = useMemo(() => gatherData(), [])
  const stats = useMemo(() => calculateStats(data, selectedType === 'monthly' ? 30 : 7), [data, selectedType])

  // Generate report
  const handleGenerate = () => {
    setIsGenerating(true)
    setTimeout(() => {
      const report = generateReport(selectedType, data, stats)
      setGeneratedReport(report)
      setIsGenerating(false)
    }, 1000)
  }

  // Download report
  const downloadReport = () => {
    if (!generatedReport) return

    const blob = new Blob([generatedReport], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `nero-${selectedType}-report-${new Date().toISOString().split('T')[0]}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  // Print report
  const printReport = () => {
    if (!generatedReport) return

    const printWindow = window.open('', '_blank')
    printWindow.document.write(`<pre style="font-family: monospace; white-space: pre-wrap;">${generatedReport}</pre>`)
    printWindow.document.close()
    printWindow.print()
  }

  // Copy to clipboard
  const copyReport = async () => {
    if (!generatedReport) return
    await navigator.clipboard.writeText(generatedReport)
  }

  return (
    <div className="h-full overflow-y-auto p-4 pb-8">
      <motion.div
        className="max-w-lg mx-auto"
        {...getMotionProps(prefersReducedMotion, {
          initial: { opacity: 0, y: 20 },
          animate: { opacity: 1, y: 0 }
        })}
      >
        {/* Header */}
        <div className="mb-6">
          <h2 className="font-display text-xl font-semibold">Export Reports</h2>
          <p className="text-sm text-white/50">Generate summaries for yourself or providers</p>
        </div>

        {/* Quick Stats */}
        <div className="grid grid-cols-3 gap-3 mb-6">
          <div className="glass-card p-3 text-center">
            <Target className="w-5 h-5 text-green-400 mx-auto mb-1" />
            <p className="text-lg font-bold">{stats.tasksCompleted}</p>
            <p className="text-xs text-white/50">Tasks</p>
          </div>
          <div className="glass-card p-3 text-center">
            <Clock className="w-5 h-5 text-purple-400 mx-auto mb-1" />
            <p className="text-lg font-bold">{Math.round(stats.focusMinutes / 60)}h</p>
            <p className="text-xs text-white/50">Focus Time</p>
          </div>
          <div className="glass-card p-3 text-center">
            <Flame className="w-5 h-5 text-orange-400 mx-auto mb-1" />
            <p className="text-lg font-bold">{stats.daysActive}</p>
            <p className="text-xs text-white/50">Days Active</p>
          </div>
        </div>

        {/* Report Type Selection */}
        <div className="mb-6">
          <h3 className="text-sm font-medium text-white/70 mb-3">Select Report Type</h3>
          <div className="space-y-2">
            {REPORT_TYPES.map((type) => {
              const Icon = type.icon
              const isSelected = selectedType === type.id

              return (
                <button
                  key={type.id}
                  onClick={() => {
                    setSelectedType(type.id)
                    setGeneratedReport(null)
                  }}
                  className={`w-full flex items-center gap-3 p-4 rounded-xl transition-all text-left ${
                    isSelected
                      ? `bg-${type.color}-500/20 border-2 border-${type.color}-500`
                      : 'bg-white/5 hover:bg-white/10 border-2 border-transparent'
                  }`}
                >
                  <div className={`w-10 h-10 rounded-lg bg-${type.color}-500/20 flex items-center justify-center`}>
                    <Icon className={`w-5 h-5 text-${type.color}-400`} />
                  </div>
                  <div className="flex-1">
                    <p className="font-medium">{type.name}</p>
                    <p className="text-xs text-white/50">{type.description}</p>
                  </div>
                  {isSelected && <CheckCircle className="w-5 h-5 text-green-400" />}
                </button>
              )
            })}
          </div>
        </div>

        {/* Generate Button */}
        <button
          onClick={handleGenerate}
          disabled={isGenerating}
          className="w-full mb-6 px-4 py-3 rounded-xl bg-nero-500 hover:bg-nero-600 text-white font-medium transition-colors disabled:opacity-50"
        >
          {isGenerating ? 'Generating...' : 'Generate Report'}
        </button>

        {/* Generated Report */}
        {generatedReport && (
          <motion.div
            {...getMotionProps(prefersReducedMotion, {
              initial: { opacity: 0, y: 20 },
              animate: { opacity: 1, y: 0 }
            })}
          >
            <div className="glass-card p-4 mb-4">
              <pre className="text-xs text-white/70 whitespace-pre-wrap font-mono max-h-64 overflow-y-auto">
                {generatedReport}
              </pre>
            </div>

            {/* Export Options */}
            <div className="flex gap-2">
              <button
                onClick={downloadReport}
                className="flex-1 flex items-center justify-center gap-2 px-4 py-2 rounded-xl bg-green-500/20 hover:bg-green-500/30 text-green-400 transition-colors"
              >
                <Download className="w-4 h-4" />
                Download
              </button>
              <button
                onClick={copyReport}
                className="flex-1 flex items-center justify-center gap-2 px-4 py-2 rounded-xl bg-blue-500/20 hover:bg-blue-500/30 text-blue-400 transition-colors"
              >
                <Share2 className="w-4 h-4" />
                Copy
              </button>
              <button
                onClick={printReport}
                className="flex-1 flex items-center justify-center gap-2 px-4 py-2 rounded-xl bg-purple-500/20 hover:bg-purple-500/30 text-purple-400 transition-colors"
              >
                <Printer className="w-4 h-4" />
                Print
              </button>
            </div>
          </motion.div>
        )}

        {/* Info */}
        <div className="mt-6 p-4 bg-white/5 rounded-xl">
          <p className="text-sm text-white/50">
            <strong className="text-white/70">Privacy Note:</strong> All reports are generated
            locally from your device. No data is sent to external servers. Share reports
            only with people you trust.
          </p>
        </div>
      </motion.div>
    </div>
  )
}
